#cloud-config

coreos:
  units:
    - name: systemd-journal-gatewayd.socket
      command: start
      enable: yes
      content: |
        [Unit] 
        Description=Journal Gateway Service Socket

        [Socket] 
        ListenStream=/var/run/journald.sock
        Service=systemd-journal-gatewayd.service

        [Install] 
        WantedBy=sockets.target
    - name: journal-2-logentries.service
      command: start
      content: |
        [Unit]
        Description=Forward Systemd Journal to logentries.com
        After=docker.service
        Requires=docker.service

        [Service]
        TimeoutStartSec=0
        ExecStartPre=-/usr/bin/docker kill journal-2-logentries
        ExecStartPre=-/usr/bin/docker rm journal-2-logentries
        ExecStartPre=/usr/bin/docker pull quay.io/kelseyhightower/journal-2-logentries
        ExecStart=/usr/bin/bash -c \
        "/usr/bin/docker run --name journal-2-logentries \
        -v /run/journald.sock:/run/journald.sock \
        -e LOGENTRIES_TOKEN=`etcdctl get /logentries.com/token` \
        quay.io/kelseyhightower/journal-2-logentries"
